Repository rajat19/lucenesaur, pull requests merged in 2022-10, with the labels that each got.

#8 Add Indic analyzer
  README.md
  build.gradle
  src/main/java/io/github/rajat19/analyzers/IndicAnalyzer.java
  src/main/java/io/github/rajat19/constants/TokenizerConstants.java
  src/main/java/io/github/rajat19/filters/DecimalDigitFilter.java
  src/main/java/io/github/rajat19/filters/IndicFilter.java
  src/main/java/io/github/rajat19/filters/IndicNormalizer.java
  src/main/java/io/github/rajat19/tokenizers/IndicTokenizer.java
  src/main/java/io/github/rajat19/tokenizers/IndicTokenizerImpl.java
  src/main/java/io/github/rajat19/tokenizers/IndicTokenizerImpl.jflex
Labels: hacktoberfest

#9 Add Decimal digit test
  src/test/java/io/github/rajat19/filters/DecimalDigitFilterTest.java
  src/test/java/io/github/rajat19/utils/FilterTestUtils.java
Labels: hacktoberfest, hacktoberfest-accepted

#14 Hindi analyser
  src/main/java/io/github/rajat19/analyzers/HindiAnalyzer.java
Labels: hacktoberfest-accepted
